apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - kind: "Pod"
              namespace: "probes"
              labels:
                app: "app-target"
              receiver: "dump"
    receivers:
      - name: "dump"
        stdout:
          layout:
            1_POD: "{{ .InvolvedObject.Name }}"
            2_AT: "{{ .LastTimestamp }}"
            3_EVENT: "{{ .Reason }}"
            4_CNT: "{{ .Count }}"
            5_MSG: "{{ .Message }}"
