---
apiVersion: v1
kind: Service
metadata:
  name: app-config
spec:
  selector:
    app: app-config
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-target
spec:
  selector:
    app: app-target
  ports:
    - protocol: TCP
      port: 3000
